### ISSUE TITLE
Scale Entire Module? 

### ISSUE THREAD

**Issue by Little-John21** [dmcinnes/MMM-forecast-io#11]
when using this module it is really big on my screen is there a way to scale the entire module? i saw i can change the graph and table but haven't been able to make the whole thing smaller?

**Comment by dmcinnes** [comment]
The easiest way is to use the `small` class like so:
```javascript
{
    module: "MMM-forecast-io",
    position: "top_right",
    classes: "small",
    config: {
      // ...
    }
}
```
Otherwise your best bet is to use custom CSS. The precipitation graph width can be changed with the `precipitationGraphWidth` config.
