### ISSUE TITLE
Graph color cannot be configured

### ISSUE THREAD

**Issue by dmcinnes** [dmcinnes/MMM-forecast-io#13]
Currently the graph color is hard coded to white, but it would be useful to be able to configure this, since it's impossible to modify using custom CSS.

**Comment by pyrosmiley** [comment]
Hi so I did some reading up on things and I *think* I got it right, but I added this as a configurable option and submitted PR #14 for it. 

Far as I can tell it's a pretty very basic thing that shouldn't mess anything else up, but please feel free to change/disregard my changes if need be. Thanks!!

**Comment by dmcinnes** [comment]
Works great, thanks :+1:
