### ISSUE TITLE
Feature Request: Indoor temperature

### ISSUE THREAD

**Issue by idoodler** [dmcinnes/MMM-forecast-io#16]
First of all, thanks for that great module!

I am owning a Smart Home and decided to develop a module that let my MagicMirror communicate with my house. I don't want to waste to much space and don't want to display too much modules.

The [default currentweather module](https://github.com/MichMich/MagicMirror/tree/develop/modules/default/currentweather) supports the `INDOOR_TEMPERATURE` notification to display the current indoor temperature.

I would love to see this  supported to maintain a clean and open design.

Thanks

**Comment by dmcinnes** [comment]
Wouldn't be opposed! I'm not currently working on this module but would happily review a PR.

**Comment by idoodler** [comment]
The PR has successfully been merged. I am closing this issue.
