### ISSUE TITLE
size

### ISSUE THREAD

**Issue by ghost** [dmcinnes/MMM-forecast-io#20]
Is there a way to make the forecast and precipitation graph smaller together?

**Comment by TylerB24890** [comment]
Also interested. I see `small` as a class in the stylesheet, but no way to implement it?

**Comment by morozgrafix** [comment]
This PR may solve this issue to some extent: https://github.com/dmcinnes/MMM-forecast-io/pull/25

**Comment by morozgrafix** [comment]
@dmcinnes we can probably close this one. thanks.
