### ISSUE TITLE
module breaks if no minutely data

### ISSUE THREAD

**Issue by lavolp3** [dmcinnes/MMM-forecast-io#26]
The module currently breaks for users that have no access to minutely data.

The problem is the following part (line 256):
`isAnyPrecipitation: function (minutely) {
    if (!minutely) {
      return false;
    }
    var data = this.weatherData.minutely.data;
    var threshold = this.config.precipitationProbabilityThreshold;
    for (i = 0; i < data.length; i++) {
      if (data[i].precipProbability > threshold) {
        return true;
      }
    }
    return false;
  },`
There needs to be an hourly distinction for users that don't have minutely data.

**Comment by morozgrafix** [comment]
can you please provide steps to reproduce this? possibly latitude and longitude for config that shows this error? if we are able to reproduce it, then we may be able to find a workaround.

**Comment by lavolp3** [comment]
I have already found a workaround changing line 256 to 
`var data = this.weatherData.minutely ? this.weatherData.minutely.data : this.weatherData.hourly.data;`

However, I'm not yet sure about the result. The graph would use hourly data instead of minutely data then.
Shows up nice but not sure if the results are comprehensible.

That is about the same procedure as some forks like @flatpepsi17's are doing it. In Europe theAPI does not provide minutely data, so maybe some more passages in the module would need to be changed.

**Comment by lavolp3** [comment]
Lat / Long config inputs are
`            latitude: 51.454,
            longitude: 6.626,
`
This is in Germany.

**Comment by lavolp3** [comment]
I now see that PR #15 and #21 treat that issue as well.
As does Issue #10 
Seems to be same underlying issue for all of them.
Sorry for raising another issue. Haven't seen that before.

**Comment by FlatPepsi17** [comment]
Earlier you cited me (Flatpepsi17) re the hourly vs minutes data. 

I agree with what you were thinking: I did that as a kludge to keep it from crashing, and wasn't sure if the output made sense. I never came back to it to think it through.

**Comment by lavolp3** [comment]
I think this is solved with recent PRs and can be closed meanwhile
