### ISSUE TITLE
No Graph

### ISSUE THREAD

**Issue by dmarkscouk** [dmcinnes/MMM-forecast-io#3]
Hi, Great to see a DarkSky fed module!!

I'm trying to get the graph to appear. My config as follows:

```
        {
            module: 'MMM-forecast-io',
            position: 'top_right',  // This can be any of the regions.
            config: {
                apiKey: 'fe479b4009d64ad9d5eea688a8540107', // Dark Sky API key.
                latitude: 51.580609,
                longitude: -0.013175,
                showForcast: true,
                showPrecipitationGraph: true,
            }
        },
```

Everything else is working, just not the graph.

Thanks, David.

**Comment by feitosa-daniel** [comment]
Hi @dmarkscouk,

I faced the same issue and had a look at the source.
I found out that it is not an issue (apparently).
[It displays the chart only if there is precipitation data to be shown:](https://github.com/dmcinnes/MMM-forecast-io/blob/f10f1cacdde19ba31bb760e269bb2ee7b1ebffb0/MMM-forecast-io.js#L161-L164)

``` javascript
if (this.config.showPrecipitationGraph && 
      this.isAnyPrecipitation(minutely)) {
  wrapper.appendChild(this.renderPrecipitationGraph());
}
```

If you want, it is possible to force creating an empty chart when there is no data:

[MMM-forecast-io.js#L161-L162](https://github.com/dmcinnes/MMM-forecast-io/blob/f10f1cacdde19ba31bb760e269bb2ee7b1ebffb0/MMM-forecast-io.js#L161-L162)

``` javascript
if (this.config.showPrecipitationGraph) { //&& 
      // this.isAnyPrecipitation(minutely)) {
  wrapper.appendChild(this.renderPrecipitationGraph());
}
```

[MMM-forecast-io.js#L220](https://github.com/dmcinnes/MMM-forecast-io/blob/f10f1cacdde19ba31bb760e269bb2ee7b1ebffb0/MMM-forecast-io.js#L220)

``` javascript
var data = this.isAnyPrecipitation(this.weatherData.minutely)? this.weatherData.minutely.data: [];
```

<img width="410" alt="screen shot 2016-10-30 at 18 42 14" src="https://cloud.githubusercontent.com/assets/1847734/19838499/bf0ab114-9ed0-11e6-835e-4c067eaa7446.png">

DISCLAIMER: I didn't test it thoroughly. 

Best, Daniel

**Comment by dmcinnes** [comment]
I've added a new config called `alwaysShowPrecipitationGraph` that will force the graph to always show even if there isn't any rain. Hope that helps!
