### ISSUE TITLE
git clone   .... nmp install needed?

### ISSUE THREAD

**Issue by 1Cedric1** [dmcinnes/MMM-forecast-io#36]
Hi,

I am interested to use your forecast module, which seems very nice.

As I did not find this information, is a "git clone ..." and "npm install" command needed to install the files ? before configuring the config file?

Thank in advance and thank you for your interest and your job!

**Comment by dmcinnes** [comment]
Hello @1Cedric1, just `git clone ...` in your modules directory is needed before modifying the config file. Enjoy!

**Comment by 1Cedric1** [comment]
Hello @dmcinnes ,
thank you for your response.
Sorry, I am new and learning...
can you please tell me the complete "git clone" command to download the files?
thank you in advance and sorry for disturbing :-)

**Comment by dmcinnes** [comment]
Hi
It should be
git clone https://github.com/dmcinnes/MMM-forecast-io.git

no problem!
