### ISSUE TITLE
Precipitation chart axis wrong?

### ISSUE THREAD

**Issue by tmatt01** [dmcinnes/MMM-forecast-io#4]
![fullsizerender](https://cloud.githubusercontent.com/assets/22587347/20038481/9ca5d0d4-a42c-11e6-941c-b4738c36b6c0.jpg)
![img_5962](https://cloud.githubusercontent.com/assets/22587347/20038492/c2be96a2-a42c-11e6-980f-69b3e0b26af3.JPG)

Huge thanks for creating this module - very impressive!

I've managed to successfully install the module and add it to config.js, however, the precipitation axis isn't rendering correctly when compared to my iPhone app.

The iPhone app is showing light rain in 20 mins (about 1/3rd of the height of the light section of the axis) which slowly raising to the start of the medium section of the axis by 60 mins.

The module shows the same start and end times but the chart basically goes from 0 to 100% instantly. This suggests to me that the y-axis is set too low. While I was able to install the module my programming skills aren't technical enough to make sense of the underlying code.

Also, one final query - is there a way to reduce the size of the text and make it closer to the size of the default weather module text?

Thanks again 

P.S. Just updated comment with screenshots!

**Comment by dmcinnes** [comment]
Sorry for the delay in response -- I've run into the same issue. I had more or less fudged the graph generation to make it look right but it appears a scaling factor is off.

**Comment by dmcinnes** [comment]
@tmatt01 I just pushed a fix, let me know how it looks to you!
