### ISSUE TITLE
Current icon is always pulled from hourly forecast and not from current

### ISSUE THREAD

**Issue by morozgrafix** [dmcinnes/MMM-forecast-io#8]
It seems that following logic is always using `hourly.icon` even if `minutely` is available.
```
var icon = minutely ? minutely.icon : hourly.icon;
var iconClass = this.config.iconTable[hourly.icon];
```
Source: https://github.com/dmcinnes/MMM-forecast-io/blob/master/MMM-forecast-io.js#L150

Also it seems since this icon is displayed for current conditions it would be better to use `currentWeather.icon` and then fall back on `hourly.icon`.

I have made that change on one of my branches and happy to submit a PR if you feel like this is a good change. 

Thanks.

**Comment by dmcinnes** [comment]
Hi sorry for the lag in response. Yes a PR would be great, thanks!
